# Your application's name
appname: "StartOlimp"

# The default layout to use for your application (located in
# views/layouts/main.tt)
# layout: "main.tpl"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

# template: "simple"

# session: "Simple"

# template: "template_toolkit"
# engines:
#   template_toolkit:
#     start_tag: '[%'
#     end_tag:   '%]'

template: Xslate
engines:
  template:
    Xslate: { path: "views" }

# template: xslate
# engines:
#     xslate:
#         # cache_dir: .xslate_cache/
#         # cache:     1
#         extension: tpl
#         # module:
#         #   - Text::Xslate::Bridge::TT2Like # to keep partial compatibility with Template Toolkit

plugins:
    Ajax:
      content_type: 'application/json'
    Thumbnail:
        cache: cache
        compression: 7
        quality: 50
